// Auto-generated by frontend-rtl-gen
// Design: apu_dma
// Module: apu_dma_core
// Generated: 2026-06-14
// Source: docs/dma/stage4_rtl_architecture.json + docs/dma/stage1_spec_extraction.json

module apu_dma_core #(
    parameter int P_INSTRUCTION_NUM    = 16,
    parameter int P_BINDWIDTH          = 64,
    parameter int P_FEATURE_MEMORY_SIZE = 65536,
    parameter int P_GROUP              = 64,
    parameter int P_WORDS_WE           = 256,
    parameter int P_BITWIDTH_WE        = 64,
    parameter int P_INNUM_MUL          = P_BITWIDTH_WE,
    parameter int P_INBITWIDTH_MUL     = 1,
    parameter int P_OUTBITWIDTH_MUL    = 1,
    parameter int P_INNUM_ADD          = P_INNUM_MUL,
    parameter int P_INBITWIDTH_ADD     = P_OUTBITWIDTH_MUL,
    parameter int P_STAGES_ADD         = $clog2(P_INNUM_ADD),
    parameter int P_OUTBITWIDTH_ADD    = P_INBITWIDTH_ADD + P_STAGES_ADD,
    parameter int P_INBITWIDTH_ACC     = 7,
    parameter int P_OUTBITWIDTH_ACC    = 12,
    parameter int P_CHANNELS           = 64,
    parameter int P_COMPAREWIDTH       = 13,
    parameter int P_TOTAL64BN          = 32
) (
    input  logic        aclk,
    input  logic        aresetn,

    input  logic        core_start,
    input  logic        core_abort,
    output logic        core_busy,
    output logic        core_done,

    input  logic        act_we,
    input  logic [ 9:0] act_waddr,
    input  logic [63:0] act_wdata,
    input  logic        out_we,
    input  logic [ 9:0] out_waddr,
    input  logic [63:0] out_wdata,
    input  logic        weight_we,
    input  logic [ 5:0] weight_bank,
    input  logic [ 7:0] weight_waddr,
    input  logic [63:0] weight_wdata,
    input  logic        bn_we,
    input  logic [ 5:0] bn_bank,
    input  logic [ 4:0] bn_waddr,
    input  logic [12:0] bn_wdata,
    input  logic        instruction_we,
    input  logic [ 3:0] instruction_waddr,
    input  logic [31:0] instruction_wdata,

    input  logic        host_rd_req,
    input  logic [ 7:0] host_rd_target,
    input  logic [ 9:0] host_rd_addr,
    output logic        host_rd_valid,
    output logic [63:0] host_rd_data
);
  localparam int P_GROUP_LOG2   = $clog2(P_GROUP);
  localparam int P_ADDRWIDTH_WE = $clog2(P_WORDS_WE);

  logic control_resetn;
  logic host_rd_target_q;

  logic        worksheet_done;
  logic        ctrl_nce;
  logic [31:0] instruction;
  logic [31:0] worksheet_data;
  logic        compute_done;

  logic [9:0] act_read_center_addr;
  logic       act_read_en;
  logic [1:0] act_kernel_size;
  logic [5:0] act_hw;
  logic [3:0] act_log_inc;
  logic [9:0] act_write_addr;
  logic       act_write_en;
  logic       input_buf_nwe;
  logic       input_buf_select;

  logic [9:0] out_read_center_addr;
  logic       out_read_en;
  logic [1:0] out_kernel_size;
  logic [5:0] out_hw;
  logic [3:0] out_log_inc;
  logic [9:0] out_write_addr;
  logic       out_write_en;

  logic [7:0] weight_addr;
  logic       weight_read_en;
  logic [4:0] bn_addr;
  logic [1:0] acc_instr;

  logic [63:0] inbuf_data;
  logic [63:0] act_data;
  logic [63:0] out_data;
  logic [63:0] weight_read_data;
  logic [P_GROUP-1:0][P_OUTBITWIDTH_ACC-1:0] compute_core_data;
  logic [P_COMPAREWIDTH-1:0] simd_read_data;
  logic [P_CHANNELS-1:0] simd_data;

  logic       host_act_read;
  logic       host_out_read;
  logic       act_mem_we;
  logic [9:0] act_mem_waddr;
  logic [63:0] act_mem_wdata;
  logic       act_mem_ce;
  logic [9:0] act_mem_raddr;
  logic [1:0] act_mem_kernel;
  logic [5:0] act_mem_hw;
  logic [3:0] act_mem_depth;
  logic       out_mem_we;
  logic [9:0] out_mem_waddr;
  logic [63:0] out_mem_wdata;
  logic       out_mem_ce;
  logic [9:0] out_mem_raddr;
  logic [1:0] out_mem_kernel;
  logic [5:0] out_mem_hw;
  logic [3:0] out_mem_depth;

  assign control_resetn = aresetn && !core_abort;
  assign host_act_read  = host_rd_req && (host_rd_target == 8'h00);
  assign host_out_read  = host_rd_req && (host_rd_target == 8'h01);

  always_ff @(posedge aclk or negedge aresetn) begin
    if (!aresetn) begin
      core_busy       <= 1'b0;
      host_rd_valid   <= 1'b0;
      host_rd_target_q <= 1'b0;
    end else begin
      host_rd_valid <= host_rd_req;
      if (host_rd_req) begin
        host_rd_target_q <= (host_rd_target == 8'h01);
      end

      if (core_abort || worksheet_done) begin
        core_busy <= 1'b0;
      end else if (core_start) begin
        core_busy <= 1'b1;
      end
    end
  end

  assign core_done    = worksheet_done;
  assign host_rd_data = host_rd_target_q ? out_data : act_data;

  WorkSheet #(
      .P_INSTRUCTION_NUM(P_INSTRUCTION_NUM)
  ) u_work_sheet (
      .clk            (aclk),
      .nRst           (control_resetn),
      .nWe            (!instruction_we),
      .iWriteAddr     (instruction_waddr),
      .iWriteData     (instruction_wdata),
      .iReadAddr      ('0),
      .iAPUReady      (core_start),
      .iComputeDone   (compute_done),
      .oWorkSheetDone (worksheet_done),
      .oWorkSheetData (worksheet_data),
      .oCtrlnCe       (ctrl_nce),
      .oInstruction   (instruction)
  );

  Ctrl #(
      .P_BINDWIDTH(P_BINDWIDTH),
      .P_FEATURE_MEMORY_SIZE(P_FEATURE_MEMORY_SIZE)
  ) u_ctrl (
      .clk                (aclk),
      .nRst               (control_resetn),
      .nCe                (ctrl_nce),
      .iInstruction       (instruction),
      .oActReadCenterAddr (act_read_center_addr),
      .oActReadEn         (act_read_en),
      .oActKernelSize     (act_kernel_size),
      .oActHW             (act_hw),
      .oActlogInC         (act_log_inc),
      .oActWriteAddr      (act_write_addr),
      .oActWriteEn        (act_write_en),
      .oInputBufNWe       (input_buf_nwe),
      .oInputBufSelect    (input_buf_select),
      .oOutReadCenterAddr (out_read_center_addr),
      .oOutReadEn         (out_read_en),
      .oOutKernelSize     (out_kernel_size),
      .oOutHW             (out_hw),
      .oOutlogInC         (out_log_inc),
      .oOutWriteAddr      (out_write_addr),
      .oOutWriteEn        (out_write_en),
      .oBNAddr            (bn_addr),
      .oWeightAddr        (weight_addr),
      .oWeightReadEn      (weight_read_en),
      .oAccInstr          (acc_instr),
      .oComputeDone       (compute_done)
  );

  InBuf #(
      .P_BINDWIDTH(P_BINDWIDTH)
  ) u_inbuf (
      .clk          (aclk),
      .nRst         (control_resetn),
      .nWe          (input_buf_nwe),
      .iWriteDataA  (act_data),
      .iWriteDataB  (out_data),
      .iSelect      (input_buf_select),
      .nCe          (1'b0),
      .oInData      (inbuf_data),
      .iInstruction (instruction)
  );

  always_comb begin
    act_mem_we     = act_we || act_write_en;
    act_mem_waddr  = act_we ? act_waddr : act_write_addr;
    act_mem_wdata  = act_we ? act_wdata : simd_data;
    act_mem_ce     = host_act_read || act_read_en;
    act_mem_raddr  = host_act_read ? host_rd_addr : act_read_center_addr;
    act_mem_kernel = host_act_read ? 2'd1 : act_kernel_size;
    act_mem_hw     = host_act_read ? 6'd1 : act_hw;
    act_mem_depth  = host_act_read ? 4'd1 : (4'd1 << (act_log_inc - 4'd6));

    out_mem_we     = out_we || out_write_en;
    out_mem_waddr  = out_we ? out_waddr : out_write_addr;
    out_mem_wdata  = out_we ? out_wdata : simd_data;
    out_mem_ce     = host_out_read || out_read_en;
    out_mem_raddr  = host_out_read ? host_rd_addr : out_read_center_addr;
    out_mem_kernel = host_out_read ? 2'd1 : out_kernel_size;
    out_mem_hw     = host_out_read ? 6'd1 : out_hw;
    out_mem_depth  = host_out_read ? 4'd1 : (4'd1 << (out_log_inc - 4'd6));
  end

  FeatureProcessor #(
      .P_FEATURE_MEMORY_SIZE(P_FEATURE_MEMORY_SIZE),
      .P_BINDWIDTH(P_BINDWIDTH)
  ) u_act_sram (
      .clk             (aclk),
      .nRst            (aresetn),
      .iReadCenterAddr (act_mem_raddr),
      .iKernelSize     (act_mem_kernel),
      .inHW            (act_mem_hw),
      .iDepth          (act_mem_depth),
      .nWe             (!act_mem_we),
      .iWriteAddr      (act_mem_waddr),
      .iWriteData      (act_mem_wdata),
      .nCe             (!act_mem_ce),
      .oFeatureData    (act_data)
  );

  FeatureProcessor #(
      .P_FEATURE_MEMORY_SIZE(P_FEATURE_MEMORY_SIZE),
      .P_BINDWIDTH(P_BINDWIDTH)
  ) u_out_sram (
      .clk             (aclk),
      .nRst            (aresetn),
      .iReadCenterAddr (out_mem_raddr),
      .iKernelSize     (out_mem_kernel),
      .inHW            (out_mem_hw),
      .iDepth          (out_mem_depth),
      .nWe             (!out_mem_we),
      .iWriteAddr      (out_mem_waddr),
      .iWriteData      (out_mem_wdata),
      .nCe             (!out_mem_ce),
      .oFeatureData    (out_data)
  );

  ComputeCoreGroup #(
      .P_GROUP(P_GROUP),
      .P_GROUP_LOG2(P_GROUP_LOG2),
      .P_WORDS_WE(P_WORDS_WE),
      .P_BITWIDTH_WE(P_BITWIDTH_WE),
      .P_ADDRWIDTH_WE(P_ADDRWIDTH_WE),
      .P_INNUM_MUL(P_INNUM_MUL),
      .P_INBITWIDTH_MUL(P_INBITWIDTH_MUL),
      .P_OUTBITWIDTH_MUL(P_OUTBITWIDTH_MUL),
      .P_INNUM_ADD(P_INNUM_ADD),
      .P_INBITWIDTH_ADD(P_INBITWIDTH_ADD),
      .P_STAGES_ADD(P_STAGES_ADD),
      .P_OUTBITWIDTH_ADD(P_OUTBITWIDTH_ADD),
      .P_INBITWIDTH_ACC(P_INBITWIDTH_ACC),
      .P_OUTBITWIDTH_ACC(P_OUTBITWIDTH_ACC)
  ) u_compute_core_group (
      .clk               (aclk),
      .nRst              (control_resetn),
      .weightData        (weight_wdata),
      .weightReadAddr    (weight_addr),
      .weightWriteAddr   (weight_waddr),
      .weightWriteSelect (weight_bank),
      .nWeightCe         (!weight_read_en),
      .nWeightWe         (!weight_we),
      .enableBuf         (!input_buf_nwe),
      .actData           (inbuf_data),
      .accInst           (acc_instr),
      .oWeightData       (weight_read_data),
      .outData           (compute_core_data)
  );

  SIMD #(
      .P_CHANNELS(P_CHANNELS),
      .P_COMPAREWIDTH(P_COMPAREWIDTH),
      .P_TOTAL64BN(P_TOTAL64BN)
  ) u_simd (
      .clk        (aclk),
      .nRst       (aresetn),
      .nWe        (!bn_we),
      .iWriteAddr (bn_waddr),
      .iChannel   (bn_bank),
      .iWriteData (bn_wdata),
      .iAddr      (bn_addr),
      .iAccData   (compute_core_data),
      .oReadData  (simd_read_data),
      .oSIMDData  (simd_data)
  );

endmodule
