// Auto-generated by frontend-rtl-gen
// Design: apu_dma
// Module: apu_job_ctrl
// Generated: 2026-06-14
// Source: docs/dma/stage4_rtl_architecture.json + docs/dma/stage1_spec_extraction.json

module apu_job_ctrl (
    input  logic        aclk,
    input  logic        aresetn,

    input  logic        cmd_valid,
    output logic        cmd_ready,
    input  logic [ 7:0] cmd_opcode,
    input  logic [ 7:0] cmd_target,
    input  logic [ 7:0] cmd_flags,
    input  logic [31:0] cmd_sequence_id,
    input  logic [31:0] cmd_payload_bytes,
    input  logic [31:0] cmd_address,
    input  logic [31:0] cmd_element_count,
    input  logic [31:0] cmd_arg0,
    input  logic [31:0] cmd_command_id,

    input  logic        decoder_error_valid,
    output logic        decoder_error_ready,
    input  logic [ 7:0] decoder_error_status,
    input  logic [31:0] decoder_error_sequence_id,
    input  logic [31:0] decoder_error_command_id,
    output logic        decoder_abort,

    output logic        loader_start_valid,
    input  logic        loader_start_ready,
    output logic [ 7:0] loader_target,
    output logic [31:0] loader_address,
    output logic [31:0] loader_element_count,
    output logic [31:0] loader_payload_bytes,
    output logic [31:0] loader_bank,
    output logic        loader_abort,
    input  logic        loader_done,
    input  logic        loader_error,
    input  logic [ 7:0] loader_error_status,

    output logic        core_start,
    output logic        core_abort,
    input  logic        core_done,
    input  logic        core_busy,

    output logic        response_start_valid,
    input  logic        response_start_ready,
    output logic [ 7:0] response_type,
    output logic [ 7:0] response_status,
    output logic [ 7:0] response_target,
    output logic [31:0] response_sequence_id,
    output logic [31:0] response_address,
    output logic [31:0] response_element_count,
    output logic [31:0] response_cycles,
    output logic [31:0] response_command_id,
    output logic        response_terminate,
    input  logic        response_done,

    output logic        job_busy,
    output logic        job_done_pulse,
    output logic        job_error_pulse,
    output logic [ 7:0] last_error,
    output logic [31:0] active_sequence_id,
    output logic [31:0] job_cycle_count
);
  import apu_dma_pkg::*;

  typedef enum logic [3:0] {
    ST_IDLE,
    ST_LOAD_START,
    ST_LOAD_WAIT,
    ST_RUN_START,
    ST_RUN_WAIT,
    ST_READ_START,
    ST_READ_WAIT,
    ST_FINAL_START,
    ST_FINAL_WAIT,
    ST_ERROR_START,
    ST_ERROR_WAIT
  } state_e;

  state_e state_q;
  logic [ 7:0] command_target_q;
  logic [31:0] command_address_q;
  logic [31:0] command_count_q;
  logic [31:0] command_payload_bytes_q;
  logic [31:0] command_arg0_q;
  logic [31:0] command_id_q;
  logic [31:0] command_sequence_q;
  logic [ 7:0] pending_error_q;
  logic [31:0] pending_error_sequence_q;
  logic [31:0] pending_error_command_q;
  logic [ 4:0] programmed_instruction_count_q;
  logic [31:0] run_cycles_q;

  function automatic logic load_target_ok(input logic [7:0] target);
    begin
      load_target_ok = (target == TARGET_ACT) || (target == TARGET_OUT) ||
                       (target == TARGET_WEIGHT) || (target == TARGET_BN) ||
                       (target == TARGET_INSTRUCTION);
    end
  endfunction

  function automatic logic result_range_ok(
      input logic [31:0] address,
      input logic [31:0] count
  );
    logic [32:0] limit;
    begin
      limit = {1'b0, address} + {1'b0, count};
      result_range_ok = (count != 0) && (limit <= 33'd1024);
    end
  endfunction

  assign cmd_ready = (state_q == ST_IDLE) && !decoder_error_valid;
  assign decoder_error_ready = (state_q != ST_ERROR_START) &&
                               (state_q != ST_ERROR_WAIT) &&
                               (state_q != ST_FINAL_START) &&
                               (state_q != ST_FINAL_WAIT);

  assign loader_start_valid   = (state_q == ST_LOAD_START);
  assign loader_target        = command_target_q;
  assign loader_address       = command_address_q;
  assign loader_element_count = command_count_q;
  assign loader_payload_bytes = command_payload_bytes_q;
  assign loader_bank          = command_arg0_q;
  assign loader_abort         = decoder_abort ||
                                (decoder_error_valid && decoder_error_ready);

  assign core_start = (state_q == ST_RUN_START) && !core_busy;

  assign response_start_valid = (state_q == ST_READ_START) ||
                                (state_q == ST_FINAL_START) ||
                                (state_q == ST_ERROR_START);

  always_comb begin
    response_type          = RESPONSE_DATA;
    response_status        = STATUS_OK;
    response_target        = command_target_q;
    response_sequence_id   = command_sequence_q;
    response_address       = command_address_q;
    response_element_count = command_count_q;
    response_cycles        = job_cycle_count;
    response_command_id    = command_id_q;
    response_terminate     = 1'b0;

    if (state_q == ST_FINAL_START) begin
      response_type          = RESPONSE_FINAL;
      response_target        = TARGET_NONE;
      response_address       = '0;
      response_element_count = '0;
      response_terminate     = 1'b1;
    end else if (state_q == ST_ERROR_START) begin
      response_type          = RESPONSE_ERROR;
      response_status        = pending_error_q;
      response_target        = TARGET_NONE;
      response_sequence_id   = pending_error_sequence_q;
      response_address       = '0;
      response_element_count = '0;
      response_command_id    = pending_error_command_q;
      response_terminate     = 1'b1;
    end
  end

  task automatic latch_command;
    begin
      command_target_q        <= cmd_target;
      command_address_q       <= cmd_address;
      command_count_q         <= cmd_element_count;
      command_payload_bytes_q <= cmd_payload_bytes;
      command_arg0_q          <= cmd_arg0;
      command_id_q            <= cmd_command_id;
      command_sequence_q      <= cmd_sequence_id;
    end
  endtask

  task automatic enter_error(
      input logic [7:0] status,
      input logic [31:0] sequence_id,
      input logic [31:0] command_id,
      input logic abort_input
  );
    begin
      pending_error_q          <= status;
      pending_error_sequence_q <= sequence_id;
      pending_error_command_q  <= command_id;
      last_error               <= status;
      decoder_abort            <= abort_input;
      core_abort               <= core_busy;
      state_q                  <= ST_ERROR_START;
    end
  endtask

  always_ff @(posedge aclk or negedge aresetn) begin
    if (!aresetn) begin
      state_q                        <= ST_IDLE;
      command_target_q               <= TARGET_NONE;
      command_address_q              <= '0;
      command_count_q                <= '0;
      command_payload_bytes_q        <= '0;
      command_arg0_q                 <= '0;
      command_id_q                   <= '0;
      command_sequence_q             <= '0;
      pending_error_q                <= STATUS_OK;
      pending_error_sequence_q       <= '0;
      pending_error_command_q        <= '0;
      programmed_instruction_count_q <= '0;
      run_cycles_q                   <= '0;
      decoder_abort                  <= 1'b0;
      core_abort                     <= 1'b0;
      job_busy                       <= 1'b0;
      job_done_pulse                 <= 1'b0;
      job_error_pulse                <= 1'b0;
      last_error                     <= STATUS_OK;
      active_sequence_id             <= '0;
      job_cycle_count                <= '0;
    end else begin
      decoder_abort   <= 1'b0;
      core_abort      <= 1'b0;
      job_done_pulse  <= 1'b0;
      job_error_pulse <= 1'b0;

      if (job_busy) begin
        job_cycle_count <= job_cycle_count + 1'b1;
      end

      if (decoder_error_valid && decoder_error_ready) begin
        pending_error_q          <= decoder_error_status;
        pending_error_sequence_q <= decoder_error_sequence_id;
        pending_error_command_q  <= decoder_error_command_id;
        last_error               <= decoder_error_status;
        core_abort               <= core_busy;
        state_q                  <= ST_ERROR_START;
      end else begin
        case (state_q)
          ST_IDLE: begin
            if (cmd_valid && cmd_ready) begin
              latch_command();

              if (!job_busy) begin
                job_busy           <= 1'b1;
                active_sequence_id <= cmd_sequence_id;
                job_cycle_count    <= '0;
                last_error         <= STATUS_OK;
              end

              if (job_busy && (cmd_sequence_id != active_sequence_id)) begin
                enter_error(STATUS_BAD_LENGTH, cmd_sequence_id, cmd_command_id,
                            cmd_opcode != OP_END_JOB);
              end else begin
                case (cmd_opcode)
                  OP_NOP: begin
                    if ((cmd_target != TARGET_NONE) || (cmd_payload_bytes != 0) ||
                        (cmd_address != 0) || (cmd_element_count != 0) || (cmd_arg0 != 0)) begin
                      enter_error(STATUS_BAD_LENGTH, cmd_sequence_id, cmd_command_id, 1'b1);
                    end
                  end

                  OP_LOAD: begin
                    if (!load_target_ok(cmd_target)) begin
                      enter_error(STATUS_BAD_TARGET, cmd_sequence_id, cmd_command_id, 1'b1);
                    end else begin
                      state_q <= ST_LOAD_START;
                    end
                  end

                  OP_RUN: begin
                    if ((cmd_target != TARGET_NONE) || (cmd_payload_bytes != 0) ||
                        (cmd_address != 0)) begin
                      enter_error(STATUS_BAD_TARGET, cmd_sequence_id, cmd_command_id, 1'b1);
                    end else if ((cmd_element_count == 0) ||
                                 (cmd_element_count > SAFE_INSTRUCTION_LIMIT) ||
                                 (cmd_element_count != programmed_instruction_count_q)) begin
                      enter_error(STATUS_RUN_WITHOUT_PROGRAM, cmd_sequence_id,
                                  cmd_command_id, 1'b1);
                    end else if ((cmd_arg0 == 0) || core_busy) begin
                      enter_error(STATUS_BUSY, cmd_sequence_id, cmd_command_id, 1'b1);
                    end else begin
                      state_q <= ST_RUN_START;
                    end
                  end

                  OP_READ_RESULT: begin
                    if ((cmd_target != TARGET_ACT) && (cmd_target != TARGET_OUT)) begin
                      enter_error(STATUS_BAD_TARGET, cmd_sequence_id, cmd_command_id, 1'b1);
                    end else if ((cmd_payload_bytes != 0) || (cmd_arg0 != 0)) begin
                      enter_error(STATUS_BAD_LENGTH, cmd_sequence_id, cmd_command_id, 1'b1);
                    end else if (!result_range_ok(cmd_address, cmd_element_count)) begin
                      enter_error(STATUS_ADDRESS_RANGE, cmd_sequence_id, cmd_command_id, 1'b1);
                    end else begin
                      state_q <= ST_READ_START;
                    end
                  end

                  OP_END_JOB: state_q <= ST_FINAL_START;

                  default: begin
                    enter_error(STATUS_BAD_OPCODE, cmd_sequence_id, cmd_command_id, 1'b1);
                  end
                endcase
              end
            end
          end

          ST_LOAD_START: begin
            if (loader_start_valid && loader_start_ready) begin
              state_q <= ST_LOAD_WAIT;
            end
          end

          ST_LOAD_WAIT: begin
            if (loader_error) begin
              enter_error(loader_error_status, command_sequence_q, command_id_q, 1'b1);
            end else if (loader_done) begin
              if (command_target_q == TARGET_INSTRUCTION) begin
                programmed_instruction_count_q <= command_count_q[4:0];
              end
              state_q <= ST_IDLE;
            end
          end

          ST_RUN_START: begin
            run_cycles_q <= '0;
            state_q      <= ST_RUN_WAIT;
          end

          ST_RUN_WAIT: begin
            run_cycles_q <= run_cycles_q + 1'b1;
            if (core_done) begin
              programmed_instruction_count_q <= '0;
              state_q <= ST_IDLE;
            end else if (run_cycles_q >= command_arg0_q - 1'b1) begin
              enter_error(STATUS_APU_TIMEOUT, command_sequence_q, command_id_q, 1'b1);
            end
          end

          ST_READ_START: begin
            if (response_start_valid && response_start_ready) begin
              state_q <= ST_READ_WAIT;
            end
          end
          ST_READ_WAIT: if (response_done) state_q <= ST_IDLE;

          ST_FINAL_START: begin
            if (response_start_valid && response_start_ready) begin
              state_q <= ST_FINAL_WAIT;
            end
          end
          ST_FINAL_WAIT: begin
            if (response_done) begin
              job_busy           <= 1'b0;
              active_sequence_id <= '0;
              job_done_pulse     <= 1'b1;
              state_q            <= ST_IDLE;
            end
          end

          ST_ERROR_START: begin
            if (response_start_valid && response_start_ready) begin
              state_q <= ST_ERROR_WAIT;
            end
          end
          ST_ERROR_WAIT: begin
            if (response_done) begin
              job_busy                        <= 1'b0;
              active_sequence_id              <= '0;
              programmed_instruction_count_q  <= '0;
              job_error_pulse                 <= 1'b1;
              state_q                         <= ST_IDLE;
            end
          end

          default: state_q <= ST_IDLE;
        endcase
      end
    end
  end

endmodule
