// Auto-generated by frontend-rtl-gen
// Design: apu_dma
// Module: apu_dma_perf_counters
// Generated: 2026-06-14
// Source: docs/dma/stage4_rtl_architecture.json + docs/dma/stage1_spec_extraction.json

module apu_dma_perf_counters (
    input  logic        aclk,
    input  logic        aresetn,
    input  logic        clear,
    input  logic        s_axis_tvalid,
    input  logic        s_axis_tready,
    input  logic [ 7:0] s_axis_tkeep,
    input  logic        m_axis_tvalid,
    input  logic        m_axis_tready,
    input  logic [ 7:0] m_axis_tkeep,
    input  logic        job_busy,
    input  logic        job_done_pulse,
    input  logic        job_error_pulse,
    output logic [63:0] rx_bytes,
    output logic [63:0] tx_bytes,
    output logic [63:0] busy_cycles,
    output logic [63:0] mm2s_stall_cycles,
    output logic [63:0] s2mm_stall_cycles,
    output logic [63:0] completed_jobs,
    output logic [63:0] error_jobs
);

  function automatic logic [3:0] keep_count(input logic [7:0] keep);
    integer i;
    begin
      keep_count = '0;
      for (i = 0; i < 8; i = i + 1) begin
        keep_count = keep_count + keep[i];
      end
    end
  endfunction

  always_ff @(posedge aclk or negedge aresetn) begin
    if (!aresetn) begin
      rx_bytes          <= '0;
      tx_bytes          <= '0;
      busy_cycles       <= '0;
      mm2s_stall_cycles <= '0;
      s2mm_stall_cycles <= '0;
      completed_jobs    <= '0;
      error_jobs        <= '0;
    end else if (clear) begin
      rx_bytes          <= '0;
      tx_bytes          <= '0;
      busy_cycles       <= '0;
      mm2s_stall_cycles <= '0;
      s2mm_stall_cycles <= '0;
      completed_jobs    <= '0;
      error_jobs        <= '0;
    end else begin
      if (s_axis_tvalid && s_axis_tready) begin
        rx_bytes <= rx_bytes + keep_count(s_axis_tkeep);
      end
      if (m_axis_tvalid && m_axis_tready) begin
        tx_bytes <= tx_bytes + keep_count(m_axis_tkeep);
      end
      if (job_busy) begin
        busy_cycles <= busy_cycles + 1'b1;
      end
      if (s_axis_tvalid && !s_axis_tready) begin
        mm2s_stall_cycles <= mm2s_stall_cycles + 1'b1;
      end
      if (m_axis_tvalid && !m_axis_tready) begin
        s2mm_stall_cycles <= s2mm_stall_cycles + 1'b1;
      end
      if (job_done_pulse) begin
        completed_jobs <= completed_jobs + 1'b1;
      end
      if (job_error_pulse) begin
        error_jobs <= error_jobs + 1'b1;
      end
    end
  end

endmodule
