// Auto-generated by frontend-rtl-gen
// Design: apu_dma
// Module: apu_dma_pkg
// Generated: 2026-06-14
// Source: docs/dma/04_STREAM_PACKET_PROTOCOL.md + docs/dma/05_RTL_IMPLEMENTATION_REVIEW.md

package apu_dma_pkg;

  parameter int unsigned AXIS_DATA_WIDTH = 64;
  parameter int unsigned AXIS_KEEP_WIDTH = AXIS_DATA_WIDTH / 8;
  parameter int unsigned HEADER_BEATS = 4;
  parameter int unsigned HEADER_BYTES = HEADER_BEATS * AXIS_KEEP_WIDTH;
  parameter int unsigned PROTOCOL_VERSION = 1;
  parameter int unsigned SAFE_INSTRUCTION_LIMIT = 15;

  localparam logic [31:0] JOB_MAGIC = 32'h4A55_5041;  // Bytes: "APUJ"
  localparam logic [31:0] RESPONSE_MAGIC = 32'h5255_5041;  // Bytes: "APUR"

  typedef enum logic [7:0] {
    OP_NOP         = 8'h00,
    OP_LOAD        = 8'h01,
    OP_RUN         = 8'h02,
    OP_READ_RESULT = 8'h03,
    OP_END_JOB     = 8'hFF
  } job_opcode_e;

  typedef enum logic [7:0] {
    TARGET_ACT         = 8'h00,
    TARGET_OUT         = 8'h01,
    TARGET_WEIGHT      = 8'h02,
    TARGET_BN          = 8'h03,
    TARGET_INSTRUCTION = 8'h04,
    TARGET_NONE        = 8'hFF
  } target_e;

  typedef enum logic [7:0] {
    RESPONSE_DATA  = 8'h01,
    RESPONSE_FINAL = 8'h02,
    RESPONSE_ERROR = 8'hFF
  } response_type_e;

  typedef enum logic [7:0] {
    STATUS_OK                  = 8'h00,
    STATUS_BAD_MAGIC           = 8'h01,
    STATUS_BAD_VERSION         = 8'h02,
    STATUS_BAD_OPCODE          = 8'h03,
    STATUS_BAD_TARGET          = 8'h04,
    STATUS_BAD_LENGTH          = 8'h05,
    STATUS_BAD_ALIGNMENT       = 8'h06,
    STATUS_ADDRESS_RANGE       = 8'h07,
    STATUS_BANK_RANGE          = 8'h08,
    STATUS_TLAST_EARLY         = 8'h09,
    STATUS_TLAST_MISSING       = 8'h0A,
    STATUS_RUN_WITHOUT_PROGRAM = 8'h0B,
    STATUS_APU_TIMEOUT         = 8'h0C,
    STATUS_BUSY                = 8'h0D,
    STATUS_INTERNAL            = 8'h7F
  } status_e;

  function automatic logic [31:0] padded_payload_bytes(input logic [31:0] bytes);
    padded_payload_bytes = (bytes + 32'd7) & 32'hFFFF_FFF8;
  endfunction

endpackage
