// Auto-generated by frontend-rtl-gen
// Design: apu_dma
// Module: apu_dma_top
// Generated: 2026-06-14
// Source: docs/dma/04_STREAM_PACKET_PROTOCOL.md + docs/dma/05_RTL_IMPLEMENTATION_REVIEW.md

module apu_dma_top #(
    parameter int AXIL_ADDR_WIDTH = 8
) (
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ACLK CLK" *)
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ACLK, ASSOCIATED_BUSIF S_AXIS_JOB:M_AXIS_RESULT:S_AXI_CTRL, ASSOCIATED_RESET ARESETN, FREQ_HZ 25000000" *)
    input  logic                       aclk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ARESETN RST" *)
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ARESETN, POLARITY ACTIVE_LOW" *)
    input  logic                       aresetn,

    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 S_AXIS_JOB TDATA" *)
    input  logic [63:0]                s_axis_job_tdata,
    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 S_AXIS_JOB TKEEP" *)
    input  logic [ 7:0]                s_axis_job_tkeep,
    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 S_AXIS_JOB TVALID" *)
    input  logic                       s_axis_job_tvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 S_AXIS_JOB TREADY" *)
    output logic                       s_axis_job_tready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 S_AXIS_JOB TLAST" *)
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME S_AXIS_JOB, TDATA_NUM_BYTES 8, HAS_TKEEP 1, HAS_TLAST 1" *)
    input  logic                       s_axis_job_tlast,

    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 M_AXIS_RESULT TDATA" *)
    output logic [63:0]                m_axis_result_tdata,
    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 M_AXIS_RESULT TKEEP" *)
    output logic [ 7:0]                m_axis_result_tkeep,
    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 M_AXIS_RESULT TVALID" *)
    output logic                       m_axis_result_tvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 M_AXIS_RESULT TREADY" *)
    input  logic                       m_axis_result_tready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 M_AXIS_RESULT TLAST" *)
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME M_AXIS_RESULT, TDATA_NUM_BYTES 8, HAS_TKEEP 1, HAS_TLAST 1" *)
    output logic                       m_axis_result_tlast,

    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI_CTRL AWADDR" *)
    input  logic [AXIL_ADDR_WIDTH-1:0] s_axil_awaddr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI_CTRL AWVALID" *)
    input  logic                       s_axil_awvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI_CTRL AWREADY" *)
    output logic                       s_axil_awready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI_CTRL WDATA" *)
    input  logic [31:0]                s_axil_wdata,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI_CTRL WSTRB" *)
    input  logic [ 3:0]                s_axil_wstrb,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI_CTRL WVALID" *)
    input  logic                       s_axil_wvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI_CTRL WREADY" *)
    output logic                       s_axil_wready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI_CTRL BRESP" *)
    output logic [ 1:0]                s_axil_bresp,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI_CTRL BVALID" *)
    output logic                       s_axil_bvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI_CTRL BREADY" *)
    input  logic                       s_axil_bready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI_CTRL ARADDR" *)
    input  logic [AXIL_ADDR_WIDTH-1:0] s_axil_araddr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI_CTRL ARVALID" *)
    input  logic                       s_axil_arvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI_CTRL ARREADY" *)
    output logic                       s_axil_arready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI_CTRL RDATA" *)
    output logic [31:0]                s_axil_rdata,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI_CTRL RRESP" *)
    output logic [ 1:0]                s_axil_rresp,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI_CTRL RVALID" *)
    output logic                       s_axil_rvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI_CTRL RREADY" *)
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME S_AXI_CTRL, PROTOCOL AXI4LITE, DATA_WIDTH 32, ADDR_WIDTH 8, READ_WRITE_MODE READ_WRITE" *)
    input  logic                       s_axil_rready,

    output logic                       irq
);
  logic        cmd_valid;
  logic        cmd_ready;
  logic [ 7:0] cmd_opcode;
  logic [ 7:0] cmd_target;
  logic [ 7:0] cmd_flags;
  logic [31:0] cmd_sequence_id;
  logic [31:0] cmd_payload_bytes;
  logic [31:0] cmd_address;
  logic [31:0] cmd_element_count;
  logic [31:0] cmd_arg0;
  logic [31:0] cmd_command_id;

  logic [63:0] payload_data;
  logic [ 7:0] payload_keep;
  logic        payload_valid;
  logic        payload_ready;
  logic        payload_last;
  logic        decoder_error_valid;
  logic        decoder_error_ready;
  logic [ 7:0] decoder_error_status;
  logic [31:0] decoder_error_sequence_id;
  logic [31:0] decoder_error_command_id;
  logic        decoder_abort;

  logic        loader_start_valid;
  logic        loader_start_ready;
  logic [ 7:0] loader_target;
  logic [31:0] loader_address;
  logic [31:0] loader_element_count;
  logic [31:0] loader_payload_bytes;
  logic [31:0] loader_bank;
  logic        loader_abort;
  logic        loader_done;
  logic        loader_error;
  logic [ 7:0] loader_error_status;

  logic        act_we;
  logic [ 9:0] act_waddr;
  logic [63:0] act_wdata;
  logic        out_we;
  logic [ 9:0] out_waddr;
  logic [63:0] out_wdata;
  logic        weight_we;
  logic [ 5:0] weight_bank;
  logic [ 7:0] weight_waddr;
  logic [63:0] weight_wdata;
  logic        bn_we;
  logic [ 5:0] bn_bank;
  logic [ 4:0] bn_waddr;
  logic [12:0] bn_wdata;
  logic        instruction_we;
  logic [ 3:0] instruction_waddr;
  logic [31:0] instruction_wdata;

  logic        core_start;
  logic        core_abort;
  logic        core_done;
  logic        core_busy;

  logic        response_start_valid;
  logic        response_start_ready;
  logic [ 7:0] response_type;
  logic [ 7:0] response_status;
  logic [ 7:0] response_target;
  logic [31:0] response_sequence_id;
  logic [31:0] response_address;
  logic [31:0] response_element_count;
  logic [31:0] response_cycles;
  logic [31:0] response_command_id;
  logic        response_terminate;
  logic        response_done;

  logic        host_rd_req;
  logic [ 7:0] host_rd_target;
  logic [ 9:0] host_rd_addr;
  logic        host_rd_valid;
  logic [63:0] host_rd_data;

  logic        job_busy;
  logic        job_done_pulse;
  logic        job_error_pulse;
  logic [ 7:0] last_error;
  logic [31:0] active_sequence_id;
  logic [31:0] job_cycle_count;
  logic        perf_clear;
  logic [63:0] rx_bytes;
  logic [63:0] tx_bytes;
  logic [63:0] busy_cycles;
  logic [63:0] mm2s_stall_cycles;
  logic [63:0] s2mm_stall_cycles;
  logic [63:0] completed_jobs;
  logic [63:0] error_jobs;

  axis_job_decoder u_decoder (
      .aclk                      (aclk),
      .aresetn                   (aresetn),
      .abort_job                 (decoder_abort),
      .s_axis_tdata              (s_axis_job_tdata),
      .s_axis_tkeep              (s_axis_job_tkeep),
      .s_axis_tvalid             (s_axis_job_tvalid),
      .s_axis_tready             (s_axis_job_tready),
      .s_axis_tlast              (s_axis_job_tlast),
      .cmd_valid                 (cmd_valid),
      .cmd_ready                 (cmd_ready),
      .cmd_opcode                (cmd_opcode),
      .cmd_target                (cmd_target),
      .cmd_flags                 (cmd_flags),
      .cmd_sequence_id           (cmd_sequence_id),
      .cmd_payload_bytes         (cmd_payload_bytes),
      .cmd_address               (cmd_address),
      .cmd_element_count         (cmd_element_count),
      .cmd_arg0                  (cmd_arg0),
      .cmd_command_id            (cmd_command_id),
      .payload_data              (payload_data),
      .payload_keep              (payload_keep),
      .payload_valid             (payload_valid),
      .payload_ready             (payload_ready),
      .payload_last              (payload_last),
      .error_valid               (decoder_error_valid),
      .error_ready               (decoder_error_ready),
      .error_status              (decoder_error_status),
      .error_sequence_id         (decoder_error_sequence_id),
      .error_command_id          (decoder_error_command_id)
  );

  apu_stream_loader u_loader (
      .aclk                  (aclk),
      .aresetn               (aresetn),
      .abort                 (loader_abort),
      .load_valid            (loader_start_valid),
      .load_ready            (loader_start_ready),
      .load_target           (loader_target),
      .load_address          (loader_address),
      .load_element_count    (loader_element_count),
      .load_payload_bytes    (loader_payload_bytes),
      .load_bank             (loader_bank),
      .payload_data          (payload_data),
      .payload_keep          (payload_keep),
      .payload_valid         (payload_valid),
      .payload_ready         (payload_ready),
      .payload_last          (payload_last),
      .load_done             (loader_done),
      .load_error            (loader_error),
      .load_error_status     (loader_error_status),
      .act_we                (act_we),
      .act_waddr             (act_waddr),
      .act_wdata             (act_wdata),
      .out_we                (out_we),
      .out_waddr             (out_waddr),
      .out_wdata             (out_wdata),
      .weight_we             (weight_we),
      .weight_bank           (weight_bank),
      .weight_waddr          (weight_waddr),
      .weight_wdata          (weight_wdata),
      .bn_we                 (bn_we),
      .bn_bank               (bn_bank),
      .bn_waddr              (bn_waddr),
      .bn_wdata              (bn_wdata),
      .instruction_we        (instruction_we),
      .instruction_waddr     (instruction_waddr),
      .instruction_wdata     (instruction_wdata)
  );

  apu_job_ctrl u_job_ctrl (
      .aclk                       (aclk),
      .aresetn                    (aresetn),
      .cmd_valid                  (cmd_valid),
      .cmd_ready                  (cmd_ready),
      .cmd_opcode                 (cmd_opcode),
      .cmd_target                 (cmd_target),
      .cmd_flags                  (cmd_flags),
      .cmd_sequence_id            (cmd_sequence_id),
      .cmd_payload_bytes          (cmd_payload_bytes),
      .cmd_address                (cmd_address),
      .cmd_element_count          (cmd_element_count),
      .cmd_arg0                   (cmd_arg0),
      .cmd_command_id             (cmd_command_id),
      .decoder_error_valid        (decoder_error_valid),
      .decoder_error_ready        (decoder_error_ready),
      .decoder_error_status       (decoder_error_status),
      .decoder_error_sequence_id  (decoder_error_sequence_id),
      .decoder_error_command_id   (decoder_error_command_id),
      .decoder_abort              (decoder_abort),
      .loader_start_valid         (loader_start_valid),
      .loader_start_ready         (loader_start_ready),
      .loader_target              (loader_target),
      .loader_address             (loader_address),
      .loader_element_count       (loader_element_count),
      .loader_payload_bytes       (loader_payload_bytes),
      .loader_bank                (loader_bank),
      .loader_abort               (loader_abort),
      .loader_done                (loader_done),
      .loader_error               (loader_error),
      .loader_error_status        (loader_error_status),
      .core_start                 (core_start),
      .core_abort                 (core_abort),
      .core_done                  (core_done),
      .core_busy                  (core_busy),
      .response_start_valid       (response_start_valid),
      .response_start_ready       (response_start_ready),
      .response_type              (response_type),
      .response_status            (response_status),
      .response_target            (response_target),
      .response_sequence_id       (response_sequence_id),
      .response_address           (response_address),
      .response_element_count     (response_element_count),
      .response_cycles            (response_cycles),
      .response_command_id        (response_command_id),
      .response_terminate         (response_terminate),
      .response_done              (response_done),
      .job_busy                   (job_busy),
      .job_done_pulse             (job_done_pulse),
      .job_error_pulse            (job_error_pulse),
      .last_error                 (last_error),
      .active_sequence_id         (active_sequence_id),
      .job_cycle_count            (job_cycle_count)
  );

  axis_result_streamer u_result_streamer (
      .aclk                 (aclk),
      .aresetn              (aresetn),
      .start_valid          (response_start_valid),
      .start_ready          (response_start_ready),
      .start_type           (response_type),
      .start_status         (response_status),
      .start_target         (response_target),
      .start_sequence_id    (response_sequence_id),
      .start_address        (response_address),
      .start_element_count  (response_element_count),
      .start_cycles         (response_cycles),
      .start_command_id     (response_command_id),
      .start_terminate      (response_terminate),
      .host_rd_req          (host_rd_req),
      .host_rd_target       (host_rd_target),
      .host_rd_addr         (host_rd_addr),
      .host_rd_valid        (host_rd_valid),
      .host_rd_data         (host_rd_data),
      .m_axis_tdata         (m_axis_result_tdata),
      .m_axis_tkeep         (m_axis_result_tkeep),
      .m_axis_tvalid        (m_axis_result_tvalid),
      .m_axis_tready        (m_axis_result_tready),
      .m_axis_tlast         (m_axis_result_tlast),
      .response_done        (response_done)
  );

  apu_dma_perf_counters u_perf (
      .aclk                (aclk),
      .aresetn             (aresetn),
      .clear               (perf_clear),
      .s_axis_tvalid       (s_axis_job_tvalid),
      .s_axis_tready       (s_axis_job_tready),
      .s_axis_tkeep        (s_axis_job_tkeep),
      .m_axis_tvalid       (m_axis_result_tvalid),
      .m_axis_tready       (m_axis_result_tready),
      .m_axis_tkeep        (m_axis_result_tkeep),
      .job_busy            (job_busy),
      .job_done_pulse      (job_done_pulse),
      .job_error_pulse     (job_error_pulse),
      .rx_bytes            (rx_bytes),
      .tx_bytes            (tx_bytes),
      .busy_cycles         (busy_cycles),
      .mm2s_stall_cycles   (mm2s_stall_cycles),
      .s2mm_stall_cycles   (s2mm_stall_cycles),
      .completed_jobs      (completed_jobs),
      .error_jobs          (error_jobs)
  );

  apu_dma_axil_regs #(
      .ADDR_WIDTH(AXIL_ADDR_WIDTH)
  ) u_axil_regs (
      .aclk                (aclk),
      .aresetn             (aresetn),
      .s_axil_awaddr       (s_axil_awaddr),
      .s_axil_awvalid      (s_axil_awvalid),
      .s_axil_awready      (s_axil_awready),
      .s_axil_wdata        (s_axil_wdata),
      .s_axil_wstrb        (s_axil_wstrb),
      .s_axil_wvalid       (s_axil_wvalid),
      .s_axil_wready       (s_axil_wready),
      .s_axil_bresp        (s_axil_bresp),
      .s_axil_bvalid       (s_axil_bvalid),
      .s_axil_bready       (s_axil_bready),
      .s_axil_araddr       (s_axil_araddr),
      .s_axil_arvalid      (s_axil_arvalid),
      .s_axil_arready      (s_axil_arready),
      .s_axil_rdata        (s_axil_rdata),
      .s_axil_rresp        (s_axil_rresp),
      .s_axil_rvalid       (s_axil_rvalid),
      .s_axil_rready       (s_axil_rready),
      .job_busy            (job_busy),
      .core_busy           (core_busy),
      .last_error          (last_error),
      .active_sequence_id  (active_sequence_id),
      .job_cycle_count     (job_cycle_count),
      .job_done_pulse      (job_done_pulse),
      .job_error_pulse     (job_error_pulse),
      .rx_bytes            (rx_bytes),
      .tx_bytes            (tx_bytes),
      .busy_cycles         (busy_cycles),
      .mm2s_stall_cycles   (mm2s_stall_cycles),
      .s2mm_stall_cycles   (s2mm_stall_cycles),
      .completed_jobs      (completed_jobs),
      .error_jobs          (error_jobs),
      .perf_clear          (perf_clear),
      .irq                 (irq)
  );

  apu_dma_core u_core (
      .aclk              (aclk),
      .aresetn           (aresetn),
      .core_start        (core_start),
      .core_abort        (core_abort),
      .core_busy         (core_busy),
      .core_done         (core_done),
      .act_we            (act_we),
      .act_waddr         (act_waddr),
      .act_wdata         (act_wdata),
      .out_we            (out_we),
      .out_waddr         (out_waddr),
      .out_wdata         (out_wdata),
      .weight_we         (weight_we),
      .weight_bank       (weight_bank),
      .weight_waddr      (weight_waddr),
      .weight_wdata      (weight_wdata),
      .bn_we             (bn_we),
      .bn_bank           (bn_bank),
      .bn_waddr          (bn_waddr),
      .bn_wdata          (bn_wdata),
      .instruction_we    (instruction_we),
      .instruction_waddr (instruction_waddr),
      .instruction_wdata (instruction_wdata),
      .host_rd_req       (host_rd_req),
      .host_rd_target    (host_rd_target),
      .host_rd_addr      (host_rd_addr),
      .host_rd_valid     (host_rd_valid),
      .host_rd_data      (host_rd_data)
  );

endmodule
