// Auto-generated by frontend-rtl-gen
// Design: apu_dma
// Module: apu_dma_axil_regs
// Generated: 2026-06-14
// Source: docs/dma/stage4_rtl_architecture.json + docs/dma/stage1_spec_extraction.json

module apu_dma_axil_regs #(
    parameter int ADDR_WIDTH = 8
) (
    input  logic                  aclk,
    input  logic                  aresetn,
    input  logic [ADDR_WIDTH-1:0] s_axil_awaddr,
    input  logic                  s_axil_awvalid,
    output logic                  s_axil_awready,
    input  logic [31:0]           s_axil_wdata,
    input  logic [ 3:0]           s_axil_wstrb,
    input  logic                  s_axil_wvalid,
    output logic                  s_axil_wready,
    output logic [ 1:0]           s_axil_bresp,
    output logic                  s_axil_bvalid,
    input  logic                  s_axil_bready,
    input  logic [ADDR_WIDTH-1:0] s_axil_araddr,
    input  logic                  s_axil_arvalid,
    output logic                  s_axil_arready,
    output logic [31:0]           s_axil_rdata,
    output logic [ 1:0]           s_axil_rresp,
    output logic                  s_axil_rvalid,
    input  logic                  s_axil_rready,

    input  logic                  job_busy,
    input  logic                  core_busy,
    input  logic [ 7:0]           last_error,
    input  logic [31:0]           active_sequence_id,
    input  logic [31:0]           job_cycle_count,
    input  logic                  job_done_pulse,
    input  logic                  job_error_pulse,
    input  logic [63:0]           rx_bytes,
    input  logic [63:0]           tx_bytes,
    input  logic [63:0]           busy_cycles,
    input  logic [63:0]           mm2s_stall_cycles,
    input  logic [63:0]           s2mm_stall_cycles,
    input  logic [63:0]           completed_jobs,
    input  logic [63:0]           error_jobs,
    output logic                  perf_clear,
    output logic                  irq
);
  import apu_dma_pkg::*;

  localparam logic [31:0] IP_ID = 32'h4455_5041; // Little-endian bytes: APUD

  logic [ADDR_WIDTH-1:0] awaddr_q;
  logic [31:0]           wdata_q;
  logic [ 3:0]           wstrb_q;
  logic                  aw_hold_q;
  logic                  w_hold_q;
  logic [ 1:0]           irq_status_q;
  logic [ 1:0]           irq_enable_q;
  logic [31:0]           read_data;

  assign s_axil_awready = !aw_hold_q && !s_axil_bvalid;
  assign s_axil_wready  = !w_hold_q && !s_axil_bvalid;
  assign s_axil_bresp   = 2'b00;
  assign s_axil_arready = !s_axil_rvalid;
  assign s_axil_rresp   = 2'b00;
  assign irq            = |(irq_status_q & irq_enable_q);

  always_comb begin
    read_data = '0;
    case (s_axil_araddr[7:0])
      8'h00: read_data = IP_ID;
      8'h04: read_data = PROTOCOL_VERSION;
      8'h08: read_data = {30'd0, core_busy, job_busy};
      8'h0C: read_data = {24'd0, last_error};
      8'h10: read_data = active_sequence_id;
      8'h14: read_data = job_cycle_count;
      8'h18: read_data = rx_bytes[31:0];
      8'h1C: read_data = rx_bytes[63:32];
      8'h20: read_data = tx_bytes[31:0];
      8'h24: read_data = tx_bytes[63:32];
      8'h28: read_data = busy_cycles[31:0];
      8'h2C: read_data = busy_cycles[63:32];
      8'h30: read_data = mm2s_stall_cycles[31:0];
      8'h34: read_data = mm2s_stall_cycles[63:32];
      8'h38: read_data = s2mm_stall_cycles[31:0];
      8'h3C: read_data = s2mm_stall_cycles[63:32];
      8'h40: read_data = completed_jobs[31:0];
      8'h44: read_data = completed_jobs[63:32];
      8'h48: read_data = error_jobs[31:0];
      8'h4C: read_data = error_jobs[63:32];
      8'h50: read_data = {30'd0, irq_status_q};
      8'h54: read_data = {30'd0, irq_enable_q};
      default: read_data = '0;
    endcase
  end

  always_ff @(posedge aclk or negedge aresetn) begin
    if (!aresetn) begin
      awaddr_q      <= '0;
      wdata_q       <= '0;
      wstrb_q       <= '0;
      aw_hold_q     <= 1'b0;
      w_hold_q      <= 1'b0;
      s_axil_bvalid <= 1'b0;
      s_axil_rdata  <= '0;
      s_axil_rvalid <= 1'b0;
      irq_status_q  <= '0;
      irq_enable_q  <= '0;
      perf_clear    <= 1'b0;
    end else begin
      perf_clear <= 1'b0;

      if (s_axil_awvalid && s_axil_awready) begin
        awaddr_q  <= s_axil_awaddr;
        aw_hold_q <= 1'b1;
      end
      if (s_axil_wvalid && s_axil_wready) begin
        wdata_q   <= s_axil_wdata;
        wstrb_q   <= s_axil_wstrb;
        w_hold_q  <= 1'b1;
      end

      if (aw_hold_q && w_hold_q && !s_axil_bvalid) begin
        case (awaddr_q[7:0])
          8'h50: irq_status_q <= irq_status_q & ~(wdata_q[1:0] &
                                                  {wstrb_q[0], wstrb_q[0]});
          8'h54: irq_enable_q <= (irq_enable_q & ~{2{wstrb_q[0]}}) |
                                    (wdata_q[1:0] & {2{wstrb_q[0]}});
          8'h58: perf_clear <= wstrb_q[0] && wdata_q[0];
          default: begin end
        endcase
        aw_hold_q     <= 1'b0;
        w_hold_q      <= 1'b0;
        s_axil_bvalid <= 1'b1;
      end else if (s_axil_bvalid && s_axil_bready) begin
        s_axil_bvalid <= 1'b0;
      end

      if (s_axil_arvalid && s_axil_arready) begin
        s_axil_rdata  <= read_data;
        s_axil_rvalid <= 1'b1;
      end else if (s_axil_rvalid && s_axil_rready) begin
        s_axil_rvalid <= 1'b0;
      end

      irq_status_q <= (irq_status_q | {job_error_pulse, job_done_pulse});
      if (aw_hold_q && w_hold_q && !s_axil_bvalid && (awaddr_q[7:0] == 8'h50)) begin
        irq_status_q <= (irq_status_q & ~(wdata_q[1:0] & {2{wstrb_q[0]}})) |
                        {job_error_pulse, job_done_pulse};
      end
    end
  end

endmodule
