// Auto-generated by frontend-rtl-gen
// Design: apu_dma
// Module: apu_stream_loader
// Source: docs/dma/stage4_rtl_architecture.json

module apu_stream_loader (
    input  logic        aclk,
    input  logic        aresetn,
    input  logic        abort,

    input  logic        load_valid,
    output logic        load_ready,
    input  logic [ 7:0] load_target,
    input  logic [31:0] load_address,
    input  logic [31:0] load_element_count,
    input  logic [31:0] load_payload_bytes,
    input  logic [31:0] load_bank,

    input  logic [63:0] payload_data,
    input  logic [ 7:0] payload_keep,
    input  logic        payload_valid,
    output logic        payload_ready,
    input  logic        payload_last,

    output logic        load_done,
    output logic        load_error,
    output logic [ 7:0] load_error_status,

    output logic        act_we,
    output logic [ 9:0] act_waddr,
    output logic [63:0] act_wdata,
    output logic        out_we,
    output logic [ 9:0] out_waddr,
    output logic [63:0] out_wdata,
    output logic        weight_we,
    output logic [ 5:0] weight_bank,
    output logic [ 7:0] weight_waddr,
    output logic [63:0] weight_wdata,
    output logic        bn_we,
    output logic [ 5:0] bn_bank,
    output logic [ 4:0] bn_waddr,
    output logic [12:0] bn_wdata,
    output logic        instruction_we,
    output logic [ 3:0] instruction_waddr,
    output logic [31:0] instruction_wdata
);
  import apu_dma_pkg::*;

  typedef enum logic [2:0] {ST_IDLE, ST_PAYLOAD, ST_HIGH32, ST_FINISH, ST_ERROR} state_e;
  state_e state_q;

  logic [ 7:0] target_q;
  logic [31:0] address_q;
  logic [31:0] elements_left_q;
  logic [31:0] bank_q;
  logic [31:0] high32_q;
  logic        finish_after_high_q;

  function automatic logic range_ok(
      input logic [7:0] target,
      input logic [31:0] address,
      input logic [31:0] count,
      input logic [31:0] bank
  );
    logic [32:0] limit;
    begin
      limit = {1'b0, address} + {1'b0, count};
      case (target)
        TARGET_ACT, TARGET_OUT: range_ok = (bank == 0) && (count != 0) && (limit <= 1024);
        TARGET_WEIGHT: range_ok = (bank < 64) && (count != 0) && (limit <= 256);
        TARGET_BN: range_ok = (bank < 64) && (count != 0) && (limit <= 32);
        TARGET_INSTRUCTION: range_ok = (bank == 0) && (count != 0) &&
                                             (address == 0) && (count <= 15);
        default: range_ok = 1'b0;
      endcase
    end
  endfunction

  function automatic logic length_ok(
      input logic [7:0] target,
      input logic [31:0] count,
      input logic [31:0] bytes
  );
    begin
      case (target)
        TARGET_ACT, TARGET_OUT, TARGET_WEIGHT: length_ok = (bytes == (count << 3));
        TARGET_BN, TARGET_INSTRUCTION: length_ok = (bytes == (count << 2));
        default: length_ok = 1'b0;
      endcase
    end
  endfunction

  assign load_ready = (state_q == ST_IDLE);
  assign payload_ready = (state_q == ST_PAYLOAD);

  task automatic write_u64(input logic [63:0] data);
    begin
      case (target_q)
        TARGET_ACT: begin
          act_we    <= 1'b1;
          act_waddr <= address_q[9:0];
          act_wdata <= data;
        end
        TARGET_OUT: begin
          out_we    <= 1'b1;
          out_waddr <= address_q[9:0];
          out_wdata <= data;
        end
        TARGET_WEIGHT: begin
          weight_we    <= 1'b1;
          weight_bank  <= bank_q[5:0];
          weight_waddr <= address_q[7:0];
          weight_wdata <= data;
        end
        default: begin end
      endcase
    end
  endtask

  task automatic write_u32(input logic [31:0] data);
    begin
      case (target_q)
        TARGET_BN: begin
          bn_we    <= 1'b1;
          bn_bank  <= bank_q[5:0];
          bn_waddr <= address_q[4:0];
          bn_wdata <= data[12:0];
        end
        TARGET_INSTRUCTION: begin
          instruction_we    <= 1'b1;
          instruction_waddr <= address_q[3:0];
          instruction_wdata <= data;
        end
        default: begin end
      endcase
    end
  endtask

  always_ff @(posedge aclk or negedge aresetn) begin
    if (!aresetn) begin
      state_q             <= ST_IDLE;
      target_q            <= TARGET_NONE;
      address_q           <= '0;
      elements_left_q     <= '0;
      bank_q              <= '0;
      high32_q            <= '0;
      finish_after_high_q <= 1'b0;
      load_done           <= 1'b0;
      load_error          <= 1'b0;
      load_error_status   <= STATUS_OK;
      act_we              <= 1'b0;
      act_waddr           <= '0;
      act_wdata           <= '0;
      out_we              <= 1'b0;
      out_waddr           <= '0;
      out_wdata           <= '0;
      weight_we           <= 1'b0;
      weight_bank         <= '0;
      weight_waddr        <= '0;
      weight_wdata        <= '0;
      bn_we               <= 1'b0;
      bn_bank             <= '0;
      bn_waddr            <= '0;
      bn_wdata            <= '0;
      instruction_we      <= 1'b0;
      instruction_waddr   <= '0;
      instruction_wdata   <= '0;
    end else begin
      load_done      <= 1'b0;
      load_error     <= 1'b0;
      act_we         <= 1'b0;
      out_we         <= 1'b0;
      weight_we      <= 1'b0;
      bn_we          <= 1'b0;
      instruction_we <= 1'b0;

      if (abort) begin
        state_q             <= ST_IDLE;
        elements_left_q     <= '0;
        finish_after_high_q <= 1'b0;
      end else case (state_q)
        ST_IDLE: begin
          if (load_valid && load_ready) begin
            target_q        <= load_target;
            address_q       <= load_address;
            elements_left_q <= load_element_count;
            bank_q          <= load_bank;
            if (!range_ok(load_target, load_address, load_element_count, load_bank)) begin
              load_error_status <= (load_bank >= 64) ? STATUS_BANK_RANGE : STATUS_ADDRESS_RANGE;
              state_q <= ST_ERROR;
            end else if (!length_ok(load_target, load_element_count, load_payload_bytes)) begin
              load_error_status <= STATUS_BAD_LENGTH;
              state_q <= ST_ERROR;
            end else begin
              state_q <= ST_PAYLOAD;
            end
          end
        end

        ST_PAYLOAD: begin
          if (payload_valid && payload_ready) begin
            if ((target_q == TARGET_ACT) || (target_q == TARGET_OUT) ||
                (target_q == TARGET_WEIGHT)) begin
              if ((payload_keep != 8'hFF) || (elements_left_q == 0) ||
                  (payload_last != (elements_left_q == 1))) begin
                load_error_status <= STATUS_BAD_LENGTH;
                state_q <= ST_ERROR;
              end else begin
                write_u64(payload_data);
                address_q       <= address_q + 1'b1;
                elements_left_q <= elements_left_q - 1'b1;
                if (elements_left_q == 1) begin
                  state_q <= ST_FINISH;
                end
              end
            end else begin
              if ((elements_left_q == 0) || (payload_keep[3:0] != 4'hF)) begin
                load_error_status <= STATUS_BAD_LENGTH;
                state_q <= ST_ERROR;
              end else begin
                write_u32(payload_data[31:0]);
                address_q       <= address_q + 1'b1;
                elements_left_q <= elements_left_q - 1'b1;
                if (elements_left_q == 1) begin
                  if (!payload_last) begin
                    load_error_status <= STATUS_BAD_LENGTH;
                    state_q <= ST_ERROR;
                  end else begin
                    state_q <= ST_FINISH;
                  end
                end else begin
                  if (payload_keep[7:4] != 4'hF) begin
                    load_error_status <= STATUS_BAD_LENGTH;
                    state_q <= ST_ERROR;
                  end else begin
                    high32_q            <= payload_data[63:32];
                    finish_after_high_q <= (elements_left_q == 2);
                    if (payload_last != (elements_left_q <= 2)) begin
                      load_error_status <= STATUS_BAD_LENGTH;
                      state_q <= ST_ERROR;
                    end else begin
                      state_q <= ST_HIGH32;
                    end
                  end
                end
              end
            end
          end
        end

        ST_HIGH32: begin
          write_u32(high32_q);
          address_q       <= address_q + 1'b1;
          elements_left_q <= elements_left_q - 1'b1;
          if (finish_after_high_q) begin
            state_q <= ST_FINISH;
          end else begin
            state_q <= ST_PAYLOAD;
          end
        end

        ST_FINISH: begin
          load_done <= 1'b1;
          state_q   <= ST_IDLE;
        end

        ST_ERROR: begin
          load_error <= 1'b1;
          state_q    <= ST_IDLE;
        end

        default: state_q <= ST_IDLE;
      endcase
    end
  end

endmodule
