// Auto-generated by frontend-rtl-gen
// Design: apu_dma
// Module: axis_job_decoder
// Source: docs/dma/stage4_rtl_architecture.json

module axis_job_decoder (
    input  logic        aclk,
    input  logic        aresetn,

    input  logic [63:0] s_axis_tdata,
    input  logic [ 7:0] s_axis_tkeep,
    input  logic        s_axis_tvalid,
    output logic        s_axis_tready,
    input  logic        s_axis_tlast,

    output logic        cmd_valid,
    input  logic        cmd_ready,
    output logic [ 7:0] cmd_opcode,
    output logic [ 7:0] cmd_target,
    output logic [ 7:0] cmd_flags,
    output logic [31:0] cmd_sequence_id,
    output logic [31:0] cmd_payload_bytes,
    output logic [31:0] cmd_address,
    output logic [31:0] cmd_element_count,
    output logic [31:0] cmd_arg0,
    output logic [31:0] cmd_command_id,

    output logic [63:0] payload_data,
    output logic [ 7:0] payload_keep,
    output logic        payload_valid,
    input  logic        payload_ready,
    output logic        payload_last,

    output logic        error_valid,
    input  logic        error_ready,
    output logic [ 7:0] error_status,
    output logic [31:0] error_sequence_id,
    output logic [31:0] error_command_id
);
  import apu_dma_pkg::*;

  typedef enum logic [2:0] {
    ST_HEADER0,
    ST_HEADER1,
    ST_HEADER2,
    ST_HEADER3,
    ST_COMMAND,
    ST_PAYLOAD,
    ST_DRAIN
  } state_e;

  state_e state_q;
  logic [63:0] header0_q;
  logic [63:0] header1_q;
  logic [63:0] header2_q;
  logic [63:0] header3_q;
  logic [31:0] payload_beats_left_q;
  logic [31:0] payload_bytes_left_q;
  logic        header_tlast_q;
  logic        drain_complete_q;

  logic [7:0] logical_keep;
  always_comb begin
    if (payload_bytes_left_q >= 32'd8) begin
      logical_keep = 8'hFF;
    end else begin
      case (payload_bytes_left_q[2:0])
        3'd0: logical_keep = 8'hFF;
        3'd1: logical_keep = 8'h01;
        3'd2: logical_keep = 8'h03;
        3'd3: logical_keep = 8'h07;
        3'd4: logical_keep = 8'h0F;
        3'd5: logical_keep = 8'h1F;
        3'd6: logical_keep = 8'h3F;
        default: logical_keep = 8'h7F;
      endcase
    end
  end

  assign cmd_opcode        = header0_q[47:40];
  assign cmd_target        = header0_q[55:48];
  assign cmd_flags         = header0_q[63:56];
  assign cmd_sequence_id   = header1_q[31:0];
  assign cmd_payload_bytes = header1_q[63:32];
  assign cmd_address       = header2_q[31:0];
  assign cmd_element_count = header2_q[63:32];
  assign cmd_arg0          = header3_q[31:0];
  assign cmd_command_id    = header3_q[63:32];

  assign cmd_valid     = (state_q == ST_COMMAND) && !error_valid;
  assign payload_data  = s_axis_tdata;
  assign payload_keep  = s_axis_tkeep & logical_keep;
  assign payload_valid = (state_q == ST_PAYLOAD) && s_axis_tvalid && !error_valid;
  assign payload_last  = (payload_beats_left_q == 32'd1);

  always_comb begin
    s_axis_tready = 1'b0;
    case (state_q)
      ST_HEADER0, ST_HEADER1, ST_HEADER2, ST_HEADER3: s_axis_tready = !error_valid;
      ST_PAYLOAD: s_axis_tready = payload_ready && !error_valid;
      ST_DRAIN: s_axis_tready = 1'b1;
      default: s_axis_tready = 1'b0;
    endcase
  end

  task automatic set_error(input logic [7:0] status, input logic drain_required);
    begin
      error_valid       <= 1'b1;
      error_status      <= status;
      error_sequence_id <= header1_q[31:0];
      error_command_id  <= header3_q[63:32];
      drain_complete_q  <= !drain_required;
      state_q           <= ST_DRAIN;
    end
  endtask

  always_ff @(posedge aclk or negedge aresetn) begin
    if (!aresetn) begin
      state_q             <= ST_HEADER0;
      header0_q           <= '0;
      header1_q           <= '0;
      header2_q           <= '0;
      header3_q           <= '0;
      payload_beats_left_q <= '0;
      payload_bytes_left_q <= '0;
      header_tlast_q      <= 1'b0;
      error_valid         <= 1'b0;
      error_status        <= STATUS_OK;
      error_sequence_id   <= '0;
      error_command_id    <= '0;
      drain_complete_q    <= 1'b0;
    end else begin
      if (error_valid && error_ready) begin
        error_valid <= 1'b0;
      end

      case (state_q)
        ST_HEADER0: begin
          if (s_axis_tvalid && s_axis_tready) begin
            header0_q <= s_axis_tdata;
            if (s_axis_tlast) begin
              header1_q <= '0;
              header3_q <= '0;
              set_error(STATUS_TLAST_EARLY, 1'b0);
            end else begin
              state_q <= ST_HEADER1;
            end
          end
        end

        ST_HEADER1: begin
          if (s_axis_tvalid && s_axis_tready) begin
            header1_q <= s_axis_tdata;
            if (s_axis_tlast) begin
              header3_q <= '0;
              set_error(STATUS_TLAST_EARLY, 1'b0);
            end else begin
              state_q <= ST_HEADER2;
            end
          end
        end

        ST_HEADER2: begin
          if (s_axis_tvalid && s_axis_tready) begin
            header2_q <= s_axis_tdata;
            if (s_axis_tlast) begin
              header3_q <= '0;
              set_error(STATUS_TLAST_EARLY, 1'b0);
            end else begin
              state_q <= ST_HEADER3;
            end
          end
        end

        ST_HEADER3: begin
          if (s_axis_tvalid && s_axis_tready) begin
            header3_q      <= s_axis_tdata;
            header_tlast_q <= s_axis_tlast;
            if (header0_q[31:0] != JOB_MAGIC) begin
              set_error(STATUS_BAD_MAGIC, !s_axis_tlast);
            end else if (header0_q[39:32] != PROTOCOL_VERSION[7:0]) begin
              set_error(STATUS_BAD_VERSION, !s_axis_tlast);
            end else if (header0_q[47:40] == OP_END_JOB) begin
              if ((header1_q[63:32] != 0) || !s_axis_tlast) begin
                set_error(s_axis_tlast ? STATUS_BAD_LENGTH : STATUS_TLAST_MISSING,
                          !s_axis_tlast);
              end else begin
                state_q <= ST_COMMAND;
              end
            end else if (s_axis_tlast) begin
              set_error(STATUS_TLAST_EARLY, 1'b0);
            end else if ((header0_q[47:40] == OP_LOAD) && (header1_q[63:32] == 0)) begin
              set_error(STATUS_BAD_LENGTH, 1'b1);
            end else if ((header0_q[47:40] != OP_LOAD) && (header1_q[63:32] != 0)) begin
              set_error(STATUS_BAD_LENGTH, 1'b1);
            end else begin
              state_q <= ST_COMMAND;
            end
          end
        end

        ST_COMMAND: begin
          if (cmd_valid && cmd_ready) begin
            if (cmd_payload_bytes != 0) begin
              payload_beats_left_q <= padded_payload_bytes(cmd_payload_bytes) >> 3;
              payload_bytes_left_q <= cmd_payload_bytes;
              state_q <= ST_PAYLOAD;
            end else begin
              state_q <= ST_HEADER0;
            end
          end
        end

        ST_PAYLOAD: begin
          if (s_axis_tvalid && s_axis_tready) begin
            if ((s_axis_tkeep & logical_keep) != logical_keep) begin
              set_error(STATUS_BAD_LENGTH, !s_axis_tlast);
            end else if (s_axis_tlast) begin
              set_error(STATUS_TLAST_EARLY, 1'b0);
            end else if (payload_beats_left_q == 32'd1) begin
              payload_beats_left_q <= '0;
              payload_bytes_left_q <= '0;
              state_q <= ST_HEADER0;
            end else begin
              payload_beats_left_q <= payload_beats_left_q - 1'b1;
              if (payload_bytes_left_q > 32'd8) begin
                payload_bytes_left_q <= payload_bytes_left_q - 32'd8;
              end else begin
                payload_bytes_left_q <= '0;
              end
            end
          end
        end

        ST_DRAIN: begin
          if (s_axis_tvalid && s_axis_tready && s_axis_tlast) begin
            drain_complete_q <= 1'b1;
          end
          if (drain_complete_q && !error_valid) begin
            state_q <= ST_HEADER0;
          end
        end

        default: state_q <= ST_HEADER0;
      endcase
    end
  end

endmodule

